extend-select = [
    "E",
    "F",
    "W",
    "I",
    "N",
    "D",
    "UP",
    "YTT",
    "ASYNC",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "G",
    "INP",
    "PIE",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SLOT",
    "SIM",
    "ERA",
    "PGH",
    "PL",
    "PERF",
    "RUF",
]
line-length = 79
ignore = [
    "D203",
    "D212",
    "S101",
    "Q000",
    "PERF203",
]
target-version = "py312"
